Final : MiniLexer.o MiniParser.o main.o 
	gcc -o Final MiniLexer.o MiniParser.o main.o -L. -l antlr3c 

main.o : main.c MiniLexer.h MiniParser.h
	gcc -c main.c -I. -I libantlr3c-3.2-win -I libantlr3c-3.2-win/include

MiniLexer.o MiniParser.o : MiniLexer.c MiniParser.c MiniLexer.h MiniParser.h 
	gcc -c MiniLexer.c MiniParser.c -I. -I libantlr3c-3.2-win -I libantlr3c-3.2-win/include

MiniLexer.c MiniParser.c MiniLexer.h MiniParser.h: Mini.g
	java -jar antlr-3.2.jar Mini.g